export const CHANGE_EXTRAS_PRICE = 'CHANGE_EXTRAS_PRICE';
export const SHOW_EXTRAS = 'SHOW_EXTRAS';
export const HIDE_EXTRAS = 'HIDE_EXTRAS';
export const ADD_CATERING = 'ADD_CATERING';
export const OPEN_GALLERY_CAROUSEL = 'OPEN_GALLERY_CAROUSEL';